var rawUserData =
{
  "login": "jmusa5",
  "id": 8901818,
  "avatar_url": "https://avatars.githubusercontent.com/u/8901818?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/jmusa5",
  "html_url": "https://github.com/jmusa5",
  "followers_url": "https://api.github.com/users/jmusa5/followers",
  "following_url": "https://api.github.com/users/jmusa5/following{/other_user}",
  "gists_url": "https://api.github.com/users/jmusa5/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/jmusa5/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/jmusa5/subscriptions",
  "organizations_url": "https://api.github.com/users/jmusa5/orgs",
  "repos_url": "https://api.github.com/users/jmusa5/repos",
  "events_url": "https://api.github.com/users/jmusa5/events{/privacy}",
  "received_events_url": "https://api.github.com/users/jmusa5/received_events",
  "type": "User",
  "site_admin": false,
  "name": "John",
  "company": "",
  "blog": "",
  "location": "",
  "email": "",
  "hireable": false,
  "bio": null,
  "public_repos": 10,
  "public_gists": 0,
  "followers": 6,
  "following": 17,
  "created_at": "2014-09-24T16:21:07Z",
  "updated_at": "2015-01-27T20:31:30Z"
};
